# Generated by Django 6.1.1 on 2026-09-14 22:54

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.knowledge.models
import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_article_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("count", models.BigIntegerField()),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("day", models.DateField()),
                (
                    "article",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="knowledge.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("article"),
                        models.F("day"),
                        django.contrib.postgres.indexes.OpClass("scope", name="varchar_pattern_ops"),
                        name="articlecount_article_scope",
                    ),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["article", "day", "scope"],
                        name="articlecount_unsquashed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=128)),
                ("tagline", models.CharField(default="", max_length=255)),
                ("footer", models.CharField(default="", max_length=255)),
                ("domain", models.CharField(max_length=128, null=True)),
                (
                    "domain_token",
                    models.CharField(
                        default=temba.knowledge.models.generate_domain_token,
                        max_length=32,
                    ),
                ),
                ("domain_verified_on", models.DateTimeField(null=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("config", models.JSONField(default=dict)),
                ("redirects", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site",
                        to="knowledge.knowledge",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("domain"),
                        condition=models.Q(("domain_verified_on__isnull", False)),
                        name="unique_verified_helpsite_domains",
                    )
                ],
            },
        ),
    ]
