# Generated by Django 6.1 on 2026-09-15 01:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_helpsite"),
        ("orgs", "0190_org_admin_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpdeskImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("import_type", models.CharField(choices=[("crisp", "Crisp")], max_length=16)),
                ("config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("O", "Processing"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("num_articles", models.IntegerField(default=0)),
                ("num_imported", models.IntegerField(default=0)),
                ("error", models.CharField(max_length=255, null=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("started_on", models.DateTimeField(null=True)),
                ("finished_on", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="imports", to="knowledge.knowledge"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="helpdesk_imports", to="orgs.org"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["knowledge", "-created_on"], name="helpdeskimport_by_created")],
            },
        ),
    ]
