# Generated by Django 5.2.13 on 2026-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0309_msg_folder"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE msgs_msg ADD COLUMN IF NOT EXISTS text_search tsvector
                GENERATED ALWAYS AS (to_tsvector('simple', text)) STORED;
            CREATE INDEX IF NOT EXISTS msgs_msg_text_search_idx ON msgs_msg USING gin(text_search);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS msgs_msg_text_search_idx;
            ALTER TABLE msgs_msg DROP COLUMN IF EXISTS text_search;
            """
        )
    ]
