# Generated by Django 5.2.13 on 2026-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0216_remove_contact_contacts_contact_org_modified_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE INDEX IF NOT EXISTS contacts_contact_name_trgm_idx ON contacts_contact USING gin (name gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS contacts_contact_name_trgm_idx;
            """
        )
    ]
